
(function(){
  const app=document.getElementById("app");
  const text={idle:"技術留給系統，故事留給使用者。",loading:"臣正在整理軍帳身份……",signed:"主公，臣已確認您的軍帳身份。",claim:"臣發現已有營寨，是否歸入此 Google 軍帳？",ready:"主公，歡迎回到您的營寨。",error:"臣今日未能與軍帳取得聯繫，請稍後再試。"};
  function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
  function layout(card,quote=text.idle){app.innerHTML=`<section class="shell"><header class="top"><div class="brand"><strong>Investment Workspace</strong><span>謀定，而後動。</span></div><div class="pill">Sprint 2 M1 · 軍帳身份</div></header><section class="grid"><aside class="zhuge"><div><div class="avatar">🪶</div><div class="zname"><b>諸葛先生</b><span>軍帳身份守門人</span></div><div class="quote">${quote}</div></div><div class="statusBox"><div class="statusLine"><span>Google OAuth</span><b>READY</b></div><div class="statusLine"><span>Supabase Auth</span><b>READY</b></div><div class="statusLine"><span>Legacy Claim</span><b>READY</b></div></div></aside><article class="card">${card}</article></section><div class="footer">同一位主公，不論任何裝置，都應回到同一座營寨。</div></section>`}
  function idle(){layout(`<div class="kicker">軍帳身份</div><h1>主公，歡迎來到 Investment Workspace。</h1><p>登入後，您的營寨、持股、策略與軍令都將跟著您的 Google 身份同步。</p><div class="actions"><button class="btn primary" id="loginBtn">使用 Google 登入</button></div>`,text.idle);document.getElementById("loginBtn").onclick=()=>window.IW_AUTH.signInWithGoogle()}
  function loading(t=text.loading){layout(`<div class="kicker">軍帳連線中</div><h1><span class="loading"></span>${t}</h1><p>請稍候，系統正在確認您的 Google 身份與營寨資料。</p>`,text.loading)}
  function error(err){layout(`<div class="kicker">連線異常</div><h1>臣今日未能與軍帳取得聯繫。</h1><p>${esc(err.message||String(err))}</p><div class="actions"><button class="btn ghost" onclick="location.reload()">重新整理</button><button class="btn primary" id="signOutBtn">重新登入</button></div>`,text.error);document.getElementById("signOutBtn").onclick=()=>window.IW_AUTH.signOut()}
  function claimPanel(auth){layout(`<div class="kicker">認領營寨</div><h1>臣發現已有營寨。</h1><p>是否將目前既有資料正式歸入此 Google 軍帳？此動作只需執行一次。</p><div class="claimCard"><small>將認領的舊有卷宗</small><b>8 筆持股 · 3 筆交易</b><span>完成後，未來登入將直接返回軍帳。</span></div><div class="userCard"><small>Google 帳號</small><b>${esc(auth.user.email||"已登入")}</b><span>UUID：${esc(auth.user.id)}</span></div><div class="actions"><button class="btn ghost" id="logoutBtn">先不要</button><button class="btn gold" id="claimBtn">立即認領營寨</button></div>`,text.claim);document.getElementById("logoutBtn").onclick=()=>window.IW_AUTH.signOut();document.getElementById("claimBtn").onclick=claim}
  function ready(summary){const row=summary?.rows?.[0];layout(`<div class="kicker">軍帳已就緒</div><h1>主公，歡迎回到您的營寨。</h1><p>身份已確認。軍帳首頁將在下一個 Sprint 接上；目前已可確認 Google、UUID 與資料認領流程。</p><div class="userCard"><small>主公</small><b>${esc(row?.display_name||"已登入")}</b><span>${esc(row?.email||"")}</span></div><div class="userCard"><small>持股 / 交易</small><b>${row?.opening_position_count??0} 筆 / ${row?.transaction_count??0} 筆</b><span>Supabase 已讀取</span></div><div class="actions"><button class="btn ghost" id="logoutBtn">登出</button><button class="btn primary" onclick="alert('軍帳首頁將於 Sprint 3 接上。')">進入軍帳</button></div>`,text.ready);document.getElementById("logoutBtn").onclick=()=>window.IW_AUTH.signOut()}
  async function claim(){try{loading("臣正在替主公認領營寨……");await window.IW_AUTH.claimLegacyWorkspace();const summary=await window.IW_AUTH.getWorkspaceSummary();ready(summary)}catch(err){error(err)}}
  async function boot(){try{loading();const auth=await window.IW_AUTH.getAuthUser();if(!auth){idle();return}const summary=await window.IW_AUTH.getWorkspaceSummary();if(summary?.rows?.length){ready(summary);return}claimPanel(auth)}catch(err){error(err)}}
  boot();
})();
